title: Show Shortcuts
description: Learn Eclipse Keyboard Shortcuts
google_analytics:
show_downloads: false
theme: jekyll-theme-architect

repository: chgeo/chgeo.github.io

plugins:
  - jekyll-mentions
  - jekyll-redirect-from

exclude:
  - node_modules
  - Gemfile*
  - package.json
  - README.md
